### ISSUE TITLE
OIDCClientId or OneLogin

### ISSUE THREAD

**Issue by maryamznegui** [aws-samples/amazon-q-slack-gateway#40]
In case of Onelogin as IDP , the  OIDCClientId will be like the following pattern : xxx-111-tyyy-123e-1234xxxxx , it will contain "-" ,  so when i tried to create the stack i got below error:
(Parameter 'OIDCClientId' must match pattern ^[a-zA-Z0-9]{1,255}$)

**Comment by avihuCohenAllCloud** [comment]
Hi, We are facing the same issue with Google Workspace OIDCClientID
