### ISSUE TITLE
[Help required] Slack setup with Okta and Amazon Q

### ISSUE THREAD

**Issue by fabseven** [aws-samples/amazon-q-slack-gateway#49]
**Describe the bug**
I have been trying to set up the Amazon Q slack gateway in our company slack workspace with Okta. I run into issues with it though when I click on the sign in button from slack -> get redirected to log in to okta -> get redirected to AWS link where the only message I get is "Internal server error". I also tried to take a look at the logs that it spits out but it doesn't really say much.

I am not sure if it's linked but we have our IAM identity center in eu-west-1 while our Amazon Q business app is located in us-east-1. Does the IAM identity center have to be in the same region for it to work properly?

**To Reproduce**
Step 1: Type "Hello" to the slackbot
Step 2: Click on "Sign in to Amazon Q"
Step 3: Redirect to Okta login page to sign in
Step 4: Redirect to AWS page with the error: "Internal server error"

**Screenshots**
![image](https://github.com/aws-samples/amazon-q-slack-gateway/assets/79915763/5e87180f-f569-4ad5-82a0-366fd1343477)
![image](https://github.com/aws-samples/amazon-q-slack-gateway/assets/79915763/59f65a7b-0547-4a91-8dfb-4eac89cc7675)

**Comment by leenmin-aws** [comment]
Yes, unfortunately cross region IdC instance is not supported at this time.

**Comment by leenmin-aws** [comment]
In fact, I believe your IAM identity center instance needs to be in the same region as the Q business app in general https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/idc-notes.html

**Comment by fabseven** [comment]
I managed to get idC in the same region and ran the scripts but it's still showing the same error but with different logs now.

![image](https://github.com/user-attachments/assets/56995111-b19d-43a9-8e48-f7365e4392a0)
![image](https://github.com/user-attachments/assets/d187cce8-ac67-41cf-a874-299e7488bcaa)

**Comment by fabseven** [comment]
Turns out it was a major identity center issue that I managed to fix
